config/routes.rb
Rails.application.routes.draw do
  
  resources :documents, only: [:index, :show, :new, :create, :destroy]
  root to: "documents#index"

  get 'signup', to: 'users#new'
  resources :users
  get 'login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'tags/:tag', to: 'documents#tagged', as: "tag"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader
  validates_presence_of :title, :description

  belongs_to :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  def self.tagged_with(name)
    Tag.find_by_name!(name).documents
  end

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
  
  def all_tags
    self.tags.map(&:name).join(", ")
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :documents, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :document
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save :downcase_email
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, 
                            format: { with: VALID_EMAIL_REGEX},         uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_secure_password

  has_many :documents, dependent: :destroy

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(self.remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  private 

    def downcase_email
      email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private 

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  before_action :logged_in_user
  before_action :correct_user, only: [:destroy]

  def index
    @documents = current_user.documents.all
  end

  def new
    @document = Document.new
  end

  def create
    #@document = Document.new(document_params)
    if logged_in?
      @document = current_user.documents.create(document_params)
      #debugger
      if @document.save
        flash[:success] = "Document uploaded successfully!"
        redirect_to documents_path
      else
        render "new"
      end
    else
      redirect_to login_path 
    end
  end

  def show
    @document = Document.find(params[:id])
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    flash[:success] = "Document Deleted!!!"
    redirect_to root_url
  end

  def tagged
    if params[:tag]
      @documents = Document.tagged_with(params[:tag]).where(user_id: current_user.id)
      #debugger
    end
  end

  private

    def document_params
      params.require(:document).permit(:title, :description, :attachment, :all_tags) 
    end

    def correct_user
      @document = current_user.documents.find_by(id: params[:id])
      redirect_to root_url if @document.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      #action
      log_in(@user)
      #remember(@user)
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      flash[:info] = "Logged in successfully!"
      redirect_to root_url
    else
      flash[:danger] = "Invalid username and password."
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    #debugger
    if @user.save
      flash[:success] = "User created successfully!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  private 

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
  def tag_links(tags)
    tags.split(",").map{ |tag| tag.strip }.join(",") 
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
    #debugger
  end

  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: session[:user_id])
    elsif (user_id = cookies.encrypted[:user_id])
      #raise
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?(user)
    user && user == current_user
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/documents/index.html.erb
<p><%= current_user.name.capitalize %></p>
<p>User Logout: <%= link_to "Log out", logout_path, method: "delete" %><p>

File Upload: <%= link_to "Upload", new_document_path %>
<div class="container">
  <ul>
    <% @documents.each do |document| %>
      <h3><%= link_to document.title, document_path(document)  %></h3>
      <!--small>
        <% document.all_tags.split(",").each do |tag| %>
          <p><%= link_to tag, tag_path(tag) %></p>
        <% end %>
      </small--> 
      <p>Tag: <% tag_links(document.all_tags).split(",").each do |tag| %>
        <%= link_to tag, tag_path(tag) %>
      <% end %></p>
      <p><%= link_to "Download File", document.attachment_url unless document.attachment_url.nil? %> 
      <%= link_to "Delete", document, method: :delete, data: { confirm: "You Sure?"} %> </p>
      <hr/>
    <% end %>
  </ul>
</div>

app/views/documents/new.html.erb
<h1>Documents</h1>

<% if !@document.errors.empty? %>   
  <div>   
    <ul>   
      <% @document.errors.full_messages.each do |msg| %>   
        <li><%= msg %></li>   
      <% end %>      
    </ul>   
  </div>   
<% end %> 

<div>   
   <%= form_for(@document)  do |f| %>   
      <p><%= f.label :title %>   
      <%= f.text_field :title %> </p>  

      <p><%= f.label :description %>   
      <%= f.text_field :description %> </p>

      <p><%= f.label :attachment %>   
      <%= f.file_field :attachment %></p>

      <p><%= f.label :tags %>   
      <%#= f.text_field :tag_ids, input_html: {multiple: true} %>
      <%= f.text_field :all_tags %></p>
         
      <%= f.submit "Save" %>   
   <% end %>   
   <p><%= link_to "back", root_url %></p>
</div>   

app/views/documents/show.html.erb
<h2><%= @document.title %></h2>
<em><%= @document.description %></em>
<p><%= link_to "Download", @document.attachment_url unless @document.attachment_url.nil? %></p>
<%= link_to "Back", root_url %> | <%= link_to "Delete", @document, method: :delete, data: { confirm: "You Sure?"} %>

app/views/documents/tagged.html.erb
<%#= @documents.tag %>
<div class="container">
  <ul>
    <% @documents.each do |document| %>
      <li><%= document.title %></li>
      <em><%= document.description %></em>
      <p><%= link_to "Download", document.attachment_url unless document.   attachment_url.nil? %> </p>
      <hr/>
    <% end %>
  </ul>
</div>
<p><%= link_to "Back", root_url %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |msg_type, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{msg_type}") %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if !@user.errors.empty? %>   
  <div>   
    <ul>   
      <% @user.errors.full_messages.each do |msg| %>   
        <li><%= msg %></li>   
      <% end %>      
    </ul>   
  </div>   
<% end %> 

<%= form_with(model: @user, local: true) do |f| %>

  <p><%= f.label :name %>
  <%= f.text_field :name, class: "form-control"  %></p>

  <p><%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %></p>

  <p><%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %></p>

  <p><%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %></p>

  <%= f.submit "submit", class: "btn btn-primary" %>

  <p>Alreday Logged in: <%= link_to "Login", login_path %>
<% end %>